### ISSUE TITLE
Manual installation instructions

### ISSUE THREAD

**Issue by butter-radish** [cryon/almost-mono-themes#4]
I'd have appreciated it if you'd specified in §'Manual installation' that almost-mono-theme.el had to be placed in my `load-path` whilst the other theme files had to be in my `custom-theme-load-path`. 

I just spent ten very confused minutes trying to get this theme to load after manually downloading the elisp file to the right place and setting my `custom-theme-load-path` only to figure out that Emacs wouldn't load the theme until it found almost-mono-theme.el—referenced by all the theme files—in my `load-path`.

**Comment by cryon** [comment]
Your appreciation have been restored.
